### ISSUE TITLE
panic: interface conversion: interface {} is string, not float64

### ISSUE THREAD

**Issue by silverscat** [mattn/go-mastodon#76]
wsClientを使って、タイムラインを取得するとpanicします。以下がエラー情報です。
```
panic: interface conversion: interface {} is string, not float64

goroutine 15 [running]:
github.com/silverscat/mastodon-go-test/vendor/github.com/mattn/go-mastodon.(*WSClient).handleWS(0xc42030d650, 0x6fa860, 0xc42001a0e8, 0xc42008b300, 0x7c, 0xc42007ce40, 0x0, 0x0)
        /home/kugo/go/src/github.com/silverscat/mastodon-go-test/vendor/github.com/mattn/go-mastodon/streaming_ws.go:130 +0x7d8
github.com/silverscat/mastodon-go-test/vendor/github.com/mattn/go-mastodon.(*WSClient).streamingWS.func1(0xc42007ce40, 0xc42030d650, 0x6fa860, 0xc42001a0e8, 0xc42011ae00)
        /home/kugo/go/src/github.com/silverscat/mastodon-go-test/vendor/github.com/mattn/go-mastodon/streaming_ws.go:71 +0x95
created by github.com/silverscat/mastodon-go-test/vendor/github.com/mattn/go-mastodon.(*WSClient).streamingWS
        /home/kugo/go/src/github.com/silverscat/mastodon-go-test/vendor/github.com/mattn/go-mastodon/streaming_ws.go:68 +0x352
exit status 2
```

以下のコードで再現
```
package main

import (
	"context"
	"fmt"
	"log"
	"regexp"

	mastodon "github.com/mattn/go-mastodon"
)

func main() {
	client := mastodon.NewClient(&mastodon.Config{Server: "https://pawoo.net", ClientID: "くらいあんとあいでー", ClientSecret: "くらいあんとしーくれっと"})
	if err := client.Authenticate(context.Background(), "いーめーる", "ぱすわーど"); err != nil {
		log.Fatal(err)
	}
	wsClient := client.NewWSClient()

	for {
		events, err := wsClient.StreamingWSPublic(context.Background(), false)
		if err != nil {
			log.Fatal(err)
		}
		for event := range events {
			if upEvent, ok := event.(*mastodon.UpdateEvent); ok {
				fmt.Println(fmt.Sprintf("%s %s %s", upEvent.Status.Account.Acct, upEvent.Status.CreatedAt.Local().Format("2006/1/2 15:04:05"), upEvent.Status.Content))
			}
		}
	}
}
```

**Comment by zetamatta** [comment]
（参考）
「pawoo.net」を「mstdn.jp」に置き換え、クライアント情報の文字列に cmd/mstdn/main.go 内の文字列を転記して、自分のアカウント（zetamatta）で再試してみましたが、パニックは起こらず、タイムラインもそれっぽく流れました。

mastodon のメジャーバージョンアップで、ツイートの ID が数値から文字列に変わり、go-mastodon も追随されたので、pawoo.netサーバーのバージョンか、ローカルにおいてあるgo-mastodonライブラリのソースコードのいずれかが古い可能性があるのではないでしょうか（pawoo.net でも追試したいところですが、クライアントIDとかの調べ方を存じ奉らず…）

**Comment by mattn** [comment]
panic のスタックトレースを見る限り古いソースの様ですね。vendor で使われている go-mastodon を更新してみて貰えますか。ID の問題は数ヶ月前に直したと思っています。

**Comment by silverscat** [comment]
depを使わず直接cloneしたものをvendorに入れたら(今のところは)クラッシュしなくなりました。ありがとうございます。
